apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: helm-server
  name: helm-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: helm-server
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: helm-server
    spec:
      containers:
      - image: "quay.io/attcomdev/ubuntu-helm:v2.1.3"
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c"]
        args: ["/bin/helm init; /bin/helm serve --address $ENDPOINT_IPADDR:8879"]
        name: helm-server
        env:
        - name: ENDPOINT_IPADDR
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        ports:
        - containerPort: 8879
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: helm-server
  name: helm-server
  namespace: default
spec:
  ports:
  - nodePort:
    port: 8879
    protocol: TCP
    targetPort: 8879
  selector:
    run: helm-server
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
